/*
  فهرست ثابت شبکه‌های ریموت
  ===========================
  هر خط یک شبکه‌ست:

    { id: "gemtv", name: "GEM TV", fa: "جم تی‌وی", cat: "movies", badge: "GEM", color: "#7b1fa2",
      streams: ["https://.../index.m3u8"], urls: ["https://www.parsatv.com/name=GEM-TV"] },

    id       شناسه‌ی یکتا با حروف لاتین (برای علاقه‌مندی‌ها، ترتیب و پنهان کردن)
    name     نام نمایشی شبکه (انگلیسی، مثل رسیور)
    fa       نام فارسی (برای جستجو)
    cat      دسته (یکی از id های SAT_CATEGORIES)
    badge    متن کوتاه لوگو (اختیاری)
    color    رنگ لوگو (اختیاری)
    streams  لینک‌های پخش مستقیم (.m3u8) که داخل خود صفحه پخش می‌شن؛ به ترتیب امتحان می‌شن
    embed    پخش یوتیوب داخل خود صفحه (اختیاری)
    urls     سایت‌های پخش شبکه؛ اگه پخش مستقیم نبود یا کار نکرد، اینا باز می‌شن

  لینک‌های پخش مستقیم از https://github.com/iptv-org/iptv برداشته شدن و ممکنه گاهی عوض بشن.
  ترتیب و شماره‌ی شبکه‌ها رو می‌شه از داخل صفحه (دکمه‌ی آبی «ویرایش») با کشیدن عوض کرد.
*/

{
window.SAT_CATEGORIES = [
  { id: "news",    name: "خبری" },
  { id: "english", name: "یادگیری زبان انگلیسی" },
  { id: "movies",  name: "فیلم و سریال" },
  { id: "iranfilm", name: "فیلم ایرانی" },
  { id: "intl",    name: "فیلم و سریال خارجی" },
  { id: "docs",    name: "مستند و تاریخی" },
  { id: "sports",  name: "ورزشی" },
  { id: "music",   name: "موسیقی" },
  { id: "kids",    name: "کودک و نوجوان" },
  { id: "general", name: "سرگرمی و عمومی" },
  { id: "iran",    name: "شبکه‌های داخلی" },
];

const P = n => `https://www.parsatv.com/name=${n}`;
// نسخه‌ی موبایل پارسا تی‌وی که داخل کادر پیش‌نمایش جا می‌شه
const PM = n => `https://www.parsatv.com/m/name=${n}`;
const PERSIANA = n => `https://${n}.persiana.live/hls/stream.m3u8`;
const WNS = n => `https://${n}.wns.live/hls/stream.m3u8`;
const TWB = n => `https://ncdn.telewebion.ir/${n}/live/playlist.m3u8`;
const TWB_SITE = n => `https://telewebion.com/live/${n}`;
// سپهر، سایت رسمی پخش زنده‌ی صداوسیما؛ داخل کادر پیش‌نمایش باز می‌شه (با VPN خاموش)
const SEPEHR = n => `https://sepehrtv.ir/live/${n}`;

window.SAT_CHANNELS = [
  /* ── خبری ── */
  { id: "iranintl", name: "Iran International", fa: "ایران اینترنشنال", cat: "news", badge: "IRAN INTL", color: "#b3121b",
    streams: ["https://hlspackager.akamaized.net/live/DB/IRAN_INTERNATIONAL/HLS/IRAN_INTERNATIONAL.m3u8", "https://live.livetvstream.co.uk/LS-63503-4/index.m3u8"],
    embed: "https://www.youtube.com/embed/live_stream?channel=UCat6bC0Wrqq9Bcq7EkH_yQw", urls: ["https://www.youtube.com/@IRANINTL/live", P("Iran-International-TV")] },
  { id: "bbcpersian", name: "BBC Persian", fa: "بی‌بی‌سی فارسی", cat: "news", badge: "BBC", color: "#a50e0e",
    streams: ["https://vs-hls-pushb-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_persian_tv/mobile_wifi_main_hd_abr_v2.m3u8",
              "https://vs-hls-pushb-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_persian_tv/pc_hd_abr_v2.m3u8"],
    urls: [P("BBC-Persian")] },
  { id: "voa", name: "VOA Persian", fa: "صدای آمریکا", cat: "news", badge: "VOA", color: "#1d4f91",
    streams: ["https://voa-ingest.akamaized.net/hls/live/2033876/tvmc07/playlist.m3u8", WNS("voaphls")], urls: [P("VOA-Persian")] },
  { id: "iranefarda", name: "Irane Farda TV", fa: "ایران فردا", cat: "news", badge: "FARDA TV", color: "#37474f",
    streams: ["https://iranefardalive.com/stream/live.m3u8"], urls: [P("Irane-Farda")] },
  { id: "dwenglish", name: "DW English", fa: "دویچه‌وله انگلیسی", cat: "english", badge: "DW", color: "#0a4d8c",
    streams: ["https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/master.m3u8",
              "https://amg01644-amg01644c1-amgplt0343.playout.now3.amagi.tv/ts-eu-w1-n2/playlist/amg01644-amg01644c1-amgplt0343/playlist.m3u8"] },
  { id: "radiofarda", name: "Radio Farda", fa: "رادیو فردا", cat: "news", badge: "فردا", color: "#c2410c",
    urls: [P("Radio-Farda"), P("Radio-Farda-TV")] },
  { id: "kanalyek", name: "Channel One", fa: "کانال یک", cat: "news", badge: "CH 1", color: "#0d47a1",
    streams: [PERSIANA("pemirateshls")], urls: [P("Channel-One")] },
  { id: "tolonews", name: "TOLOnews", fa: "طلوع نیوز", cat: "news", badge: "TOLO NEWS", color: "#c62828",
    streams: ["https://tgn.bozztv.com/eshgtv-dvrfl05/gin-tolonews/index.m3u8"] },

  /* ── یادگیری زبان انگلیسی (اخبار و برنامه‌های انگلیسی‌زبان با لهجه‌های مختلف) ── */
  { id: "bbcnews", name: "BBC News", fa: "بی‌بی‌سی نیوز", cat: "english", streams: ["https://vs-hls-push-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_news_channel_hd/mobile_wifi_main_hd_abr_v2.m3u8"] },
  { id: "aljazeeraen", name: "Al Jazeera English", fa: "الجزیره انگلیسی", cat: "english", streams: ["https://live-hls-apps-aje-fa.getaj.net/AJE/index.m3u8"] },
  { id: "france24en", name: "France 24 English", fa: "فرانس ۲۴ انگلیسی", cat: "english", streams: ["https://live.france24.com/hls/live/2037218-b/F24_EN_HI_HLS/master_5000.m3u8"] },
  { id: "nhkworld", subs: true, name: "NHK World-Japan", fa: "ان‌اچ‌کی ژاپن", cat: "english", streams: ["https://masterpl.hls.nhkworld.jp/hls/w/live/smarttv.m3u8"] },
  { id: "trtworld", name: "TRT World", fa: "تی‌آر‌تی ورلد", cat: "english", streams: ["https://mumbai-edge.smartplaytv.in/TRTWorld/index.m3u8", "https://dash2.antik.sk/live/test_trt_world_atktv/playlist.m3u8"] },
  { id: "cgtnen", name: "CGTN English", fa: "سی‌جی‌تی‌ان انگلیسی", cat: "english", streams: ["https://amg00405-rakutentv-cgtn-rakuten-i9tar.amagi.tv/master.m3u8", "https://h5cul1yar48um3t.wcetv.com/hls/cgtn.m3u8"] },
  { id: "abcnews", name: "ABC News Live", fa: "ای‌بی‌سی نیوز", cat: "english", streams: ["https://abcnews-streams.akamaized.net/hls/live/2023560/abcnewshudson1/master.m3u8", "https://abcnews-streams.akamaized.net/hls/live/2023561/abcnewshudson2/master.m3u8"] },
  { id: "cbsnewsny", name: "CBS News New York", fa: "سی‌بی‌اس نیوز", cat: "english", streams: ["https://cbsn-ny.cbsnstream.cbsnews.com/out/v1/ec3897d58a9b45129a77d67aa247d136/master.m3u8"] },
  { id: "nbcnewsnow", subs: true, name: "NBC News NOW", fa: "ان‌بی‌سی نیوز", cat: "english", streams: ["https://aegis-cloudfront-1.tubi.video/605fb6ea-f89c-451a-873c-030cb726b493/master.m3u8", "https://d1si3n1st4nkgb.cloudfront.net/10502/88896001/hls/master.m3u8?ads.xumo_channelId=88896001"] },
  { id: "abcau", subs: true, name: "ABC News Australia", fa: "ای‌بی‌سی استرالیا", cat: "english", streams: ["https://abc-news-dmd-streams-1.akamaized.net/out/v1/701126012d044971b3fa89406a440133/index.m3u8"] },
  { id: "reuters", subs: true, name: "Reuters", fa: "رویترز", cat: "english", streams: ["https://amg00453-reuters-amg00453c1-rakuten-uk-2110.playouts.now.amagi.tv/playlist/amg00453-reuters-reuters-rakutenuk/playlist.m3u8", "https://amg00453-reuters-amg00453c1-xumo-us-2073.playouts.now.amagi.tv/reuters-reuters-hls/playlist.m3u8"] },
  { id: "bloomberg", subs: true, name: "Bloomberg TV", fa: "بلومبرگ", cat: "english", streams: ["https://bloomberg.com/media-manifest/streams/us.m3u8", "https://bloomberg.com/media-manifest/streams/eu.m3u8"] },
  { id: "cnaorig", name: "CNA Originals", fa: "سی‌ان‌ای", cat: "english", streams: ["https://amg01082-cna-amg01082c1-rlaxx-us-11304.playouts.now.amagi.tv/playlist.m3u8"] },
  { id: "arirang", name: "Arirang TV", fa: "آریرانگ", cat: "english", streams: ["https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8"] },
  { id: "i24en", name: "i24NEWS English", fa: "آی۲۴ انگلیسی", cat: "english", streams: ["https://i24newsenglish-cdn.encoders.immergo.tv/master.m3u8"] },
  { id: "wion", name: "WION", fa: "وایون", cat: "english", streams: ["https://d7x8z4yuq42qn.cloudfront.net/index_7.m3u8"] },
  { id: "africanews", name: "Africanews English", fa: "آفریکانیوز", cat: "english", streams: ["https://cdn-euronews.akamaized.net/live/eds/africanews-en/25049/index.m3u8"] },
  { id: "ted", name: "TED", fa: "تد (سخنرانی‌ها)", cat: "english", streams: ["https://d1b16tvvxk3tnu.cloudfront.net/TED.m3u8"] },
  { id: "pbskids", subs: true, name: "PBS Kids", fa: "پی‌بی‌اس کیدز", cat: "english", streams: ["https://livestream.pbskids.org/out/v1/14507d931bbe48a69287e4850e53443c/est.m3u8", "https://livestream.pbskids.org/out/v1/11f2e6b73eaa4887b3746cb863960e79/pst.m3u8"] },
  { id: "mrbean", name: "Mr Bean Animated", fa: "مستر بین کارتونی", cat: "english", streams: ["https://amg00627-amg00627c23-samsung-gb-3927.playouts.now.amagi.tv/playlist.m3u8"] },
  { id: "mrbeanlive", subs: true, name: "Mr Bean Live Action", fa: "مستر بین", cat: "english", streams: ["https://amg00627-amg00627c40-rakuten-uk-5725.playouts.now.amagi.tv/playlist/amg00627-banijayfast-mrbeanpopupcc-rakutenuk/playlist.m3u8"] },
  { id: "moviesphere", subs: true, name: "MovieSphere", fa: "فیلم انگلیسی", cat: "english", streams: ["https://aegis-cloudfront-1.tubi.video/8b127a5b-3054-4f39-93a2-1c4aab9ef5ff/playlist.m3u8", "https://moviesphereuk-samsunguk.amagi.tv/playlist.m3u8"] },
  { id: "classicarts", name: "Classic Arts Showcase", fa: "هنر کلاسیک", cat: "english", streams: ["https://classicarts.akamaized.net/hls/live/1024257/CAS/master.m3u8"] },

  /* ── فیلم و سریال ── */
  { id: "4utv", name: "4U", fa: "فوریو", cat: "movies", badge: "4U", color: "#e91e63", streams: [], embed: PM("4U-TV"), urls: [P("4U-TV")] },
  { id: "4ufamily", name: "4U Family", fa: "فوریو فمیلی", cat: "movies", badge: "4U FAMILY", color: "#ec407a", streams: [], embed: PM("4U-Family"), urls: [P("4U-Family")] },
  { id: "romanticotv", name: "Romantico TV", fa: "رومانتیکو", cat: "movies", badge: "ROMANTICO", color: "#c2185b", streams: [], embed: PM("Romantico-TV"), urls: [P("Romantico-TV")] },
  { id: "gemtv", name: "GEM TV", fa: "جم تی‌وی", cat: "movies", badge: "GEM", color: "#7b1fa2", streams: [], embed: PM("GEM-TV"), urls: [P("GEM-TV")] },
  { id: "gemseries", name: "GEM Series", fa: "جم سریال", cat: "movies", badge: "GEM SERIES", color: "#8e24aa", streams: [], embed: PM("GEM-Series-TV"), urls: [P("GEM-Series-TV")] },
  { id: "gemfilm", name: "GEM Film", fa: "جم فیلم", cat: "movies", badge: "GEM FILM", color: "#6a1b9a", streams: [], embed: PM("GEM-Film"), urls: [P("GEM-Film")] },
  { id: "gemclassic", name: "GEM Classic", fa: "جم کلاسیک", cat: "movies", badge: "CLASSIC", color: "#5d4037", streams: [], embed: PM("GEM-Classic"), urls: [P("GEM-Classic")] },
  { id: "gemonyx", name: "GEM Onyx", fa: "جم اونیکس", cat: "movies", badge: "ONYX", color: "#212121", streams: [], embed: PM("GEM-Onyx"), urls: [P("GEM-Onyx")] },
  { id: "gemdrama", name: "GEM Drama", fa: "جم درام", cat: "movies", badge: "GEM DRAMA", color: "#ad1457", streams: [], embed: PM("GEM-Drama"), urls: [P("GEM-Drama")] },
  { id: "gemriver", name: "GEM River", fa: "جم ریور", cat: "movies", badge: "GEM RIVER", color: "#00796b", streams: [], embed: PM("GEM-River"), urls: [P("GEM-River")] },
  { id: "gemrubix", name: "GEM Rubix", fa: "جم روبیکس", cat: "movies", badge: "RUBIX", color: "#e65100", streams: [], embed: PM("GEM-Rubix"), urls: [P("GEM-Rubix")] },
  { id: "gembollywood", name: "GEM Bollywood", fa: "جم بالیوود", cat: "movies", badge: "BOLLYWOOD", color: "#c2185b", streams: [], embed: PM("GEM-Bollywood"), urls: [P("GEM-Bollywood")] },
  { id: "gemcomedy", name: "GEM Comedy", fa: "جم کمدی", cat: "movies", badge: "GEM COMEDY", color: "#f57f17", streams: [], embed: PM("GEM-Comedy"), urls: [P("GEM-Comedy")] },
  { id: "persianacinema", name: "Persiana Cinema", fa: "پرشیانا سینما", cat: "movies", badge: "PERSIANA CINEMA", color: "#b71c1c",
    streams: [PERSIANA("cinehls"), WNS("todayhls")], urls: [P("Persiana-Cinema")] },
  { id: "persianaseries", name: "Persiana Series", fa: "پرشیانا سریال", cat: "movies", badge: "PERSIANA SERIES", color: "#c62828", streams: [PERSIANA("onehls")] },
  { id: "persianairanian", name: "Persiana Iranian", fa: "پرشیانا ایرانیان", cat: "iranfilm", badge: "IRANIAN", color: "#880e4f", streams: [PERSIANA("irhls")], urls: [P("Persiana-Iranian")] },
  { id: "persiananostalgia", name: "Persiana Nostalgia", fa: "پرشیانا نوستالژی", cat: "iranfilm", badge: "NOSTALGIA", color: "#795548", streams: [PERSIANA("noshls")] },
  { id: "persianakorea", name: "Persiana Korea", fa: "پرشیانا کره", cat: "movies", badge: "KOREA", color: "#1565c0", streams: [PERSIANA("korhls")] },
  { id: "persianaturkiye", name: "Persiana Turkiye", fa: "پرشیانا ترکیه", cat: "movies", badge: "TÜRKİYE", color: "#c62828", streams: [PERSIANA("turkhls")] },
  { id: "persianalatino", name: "Persiana Latino", fa: "پرشیانا لاتین", cat: "movies", badge: "LATINO", color: "#ef6c00", streams: [PERSIANA("latinohls")] },
  { id: "mbcpersia", name: "MBC Persia", fa: "ام‌بی‌سی پرشیا", cat: "movies", badge: "MBC", color: "#1565c0",
    streams: ["https://hls.mbcpersia.live/hls/stream.m3u8", "https://shd-gcp-live.edgenextcdn.net/live/bitmovin-mbc-persia/818ee8e4b592dc497608f066d825bfb4/index.m3u8"],
    urls: [P("MBC-Persia")] },
  { id: "afrafilm", name: "Afra Film", fa: "افرا فیلم", cat: "movies", badge: "AFRA FILM", color: "#4e342e", streams: [WNS("afrafhls")] },
  { id: "afraseries", name: "Afra Series", fa: "افرا سریال", cat: "movies", badge: "AFRA SERIES", color: "#5d4037", streams: [WNS("afrashls")] },
  { id: "avaseries", name: "AVA Series", fa: "آوا سریال", cat: "movies", badge: "AVA SERIES", color: "#283593", streams: [WNS("avaserieshls")] },
  { id: "grandcinema", name: "Grand Cinema", fa: "گرند سینما", cat: "movies", badge: "GRAND CINEMA", color: "#3e2723", streams: [WNS("gcinemahls")] },
  { id: "cafefilm", name: "Cafe Film", fa: "کافه فیلم", cat: "movies", badge: "CAFE FILM", color: "#6d4c41", streams: [WNS("cafefhls")] },
  { id: "goldstar", name: "Gold Star", fa: "گلد استار", cat: "movies", badge: "GOLD STAR", color: "#b8860b", streams: [WNS("moviethls")] },
  { id: "metafilm", name: "Meta Film", fa: "متا فیلم", cat: "movies", badge: "META FILM", color: "#4527a0", streams: [WNS("metafilmhls")] },
  { id: "newflix", name: "Newflix", fa: "نیوفلیکس", cat: "movies", badge: "NEWFLIX", color: "#b71c1c", streams: [WNS("newfhls")] },
  { id: "ekranmovies", name: "Ekran Movies", fa: "اکران مووی", cat: "movies", badge: "EKRAN", color: "#37474f", streams: [], embed: PM("Ekran-Movies"), urls: [P("Ekran-Movies")] },
  { id: "t2movies", name: "T2 Movies", fa: "تی۲ مووی", cat: "movies", badge: "T2 MOVIES", color: "#00838f", streams: [], embed: PM("T2-Movies"), urls: [P("T2-Movies")] },
  { id: "classictv", name: "Classic TV", fa: "کلاسیک تی‌وی", cat: "iranfilm", badge: "CLASSIC TV", color: "#4e342e", streams: [WNS("clshls")] },
  { id: "khatereh", name: "Khatereh TV", fa: "خاطره", cat: "iranfilm", badge: "خاطره", color: "#6d4c41", urls: [P("Khatereh-TV")] },
  { id: "ifilm", name: "iFilm", fa: "آی‌فیلم", cat: "iranfilm", badge: "iFILM", color: "#c77800",
    streams: [TWB("ifilm"), "https://live.presstv.ir/hls/ifilmfa.m3u8"], embed: SEPEHR("ifilm"), urls: [SEPEHR("ifilm"), TWB_SITE("ifilm"), P("iFilm-Persian")] },
  { id: "ifilm2", name: "iFilm 2", fa: "آی‌فیلم ۲", cat: "iranfilm", badge: "iFILM 2", color: "#a35f00",
    streams: ["https://live.presstv.ir/hls/ifilm2.m3u8"], embed: SEPEHR("ifilmdari"), urls: ["https://fa2.ifilmtv.ir/Home/Live", SEPEHR("ifilmdari")] },
  { id: "namayesh", name: "IRIB Namayesh", fa: "نمایش", cat: "iranfilm", badge: "نمایش", color: "#5e35b1", streams: [TWB("namayesh")], embed: SEPEHR("namayesh"), urls: [SEPEHR("namayesh"), TWB_SITE("namayesh")] },
  { id: "tamasha", name: "IRIB Tamasha", fa: "تماشا", cat: "movies", badge: "تماشا", color: "#283593", streams: [TWB("hdtest")], embed: SEPEHR("tamasha"), urls: [SEPEHR("tamasha"), TWB_SITE("hdtest")] },
  { id: "ytfilms", name: "YouTube Movies", fa: "فیلم‌های یوتیوب", cat: "movies", badge: "YouTube", color: "#d32f2f", embed: "https://www.youtube.com/embed/videoseries?list=UUlgRkhTL3_hImCAmdLfDE4g", urls: ["https://www.youtube.com/channel/UClgRkhTL3_hImCAmdLfDE4g"] },

  /* ── مستند و تاریخی ── */
  { id: "mostanad", name: "IRIB Mostanad", fa: "شبکه مستند", cat: "docs", badge: "مستند", color: "#2e7d32",
    streams: [TWB("mostanad")], embed: SEPEHR("mostanad"), urls: [SEPEHR("mostanad"), TWB_SITE("mostanad"), P("Mostanad")] },
  { id: "tv4", name: "IRIB TV4", fa: "شبکه چهار", cat: "docs", badge: "۴", color: "#00695c", streams: [TWB("tv4")], embed: SEPEHR("tv4"), urls: [SEPEHR("tv4"), TWB_SITE("tv4")] },
  { id: "persianadocs", name: "Persiana Docs", fa: "پرشیانا مستند", cat: "docs", badge: "PERSIANA DOCS", color: "#33691e", streams: [PERSIANA("scihls")] },
  { id: "persianatravel", name: "Persiana Travel", fa: "پرشیانا سفر", cat: "docs", badge: "TRAVEL", color: "#0277bd", streams: [PERSIANA("ptravelhls"), WNS("mardomhls")] },
  { id: "persianamedical", name: "Persiana Medical", fa: "پرشیانا پزشکی", cat: "docs", badge: "MEDICAL", color: "#00838f", streams: [PERSIANA("phd2hls"), WNS("tfnhls")] },
  { id: "gemnature", name: "GEM Nature", fa: "جم نیچر", cat: "docs", badge: "GEM NATURE", color: "#2e7d32", streams: [], embed: PM("GEM-Nature"), urls: [P("GEM-Nature")] },
  { id: "manotodocs", name: "Manoto Documentaries", fa: "مستندهای منوتو", cat: "docs", badge: "manoto", color: "#37474f",
    embed: "https://www.youtube.com/embed/videoseries?list=PLK_tIl1mumy8EHJtlHd0H_omDgqKGsrwu", urls: ["https://www.youtube.com/playlist?list=PLK_tIl1mumy8EHJtlHd0H_omDgqKGsrwu"] },
  { id: "historyhit", subs: true, name: "History Hit", fa: "History Hit (تاریخی)", cat: "docs", badge: "HISTORY HIT", color: "#7f1d1d", streams: ["https://lds-timeline-rakuten.amagi.tv/playlist.m3u8"] },
  { id: "historyhunters", subs: true, name: "History Hunters", fa: "History Hunters (تاریخی)", cat: "docs", badge: "HISTORY", color: "#6d4c41",
    streams: ["https://amg00841-amg00841c7-rakuten-uk-2820.playouts.now.amagi.tv/playlist/amg00841-aeemeafast-historyhuntersrakuten-rakutenuk/playlist.m3u8"] },
  { id: "truehistory", subs: true, name: "True History", fa: "True History (تاریخی)", cat: "docs", badge: "TRUE HISTORY", color: "#5d4037",
    streams: ["https://linear-188.frequency.stream/dist/glewedtv/188/hls/master/playlist.m3u8"] },
  { id: "cgtndoc", name: "CGTN Documentary", fa: "CGTN Documentary", cat: "docs", badge: "CGTN DOC", color: "#0d47a1",
    streams: ["https://hlspackager.akamaized.net/live/DB/CGTN_DOCUMENTARY/HLS/CGTN_DOCUMENTARY.m3u8", "https://global.cgtn.cicc.media.caton.cloud/master/cgtn-documentary.m3u8"] },
  { id: "docplus", subs: true, name: "Documentary+", fa: "Documentary+", cat: "docs", badge: "DOC+", color: "#263238",
    streams: ["https://ef79b15c8c7c46c7a9de9d33001dbd07.mediatailor.us-west-2.amazonaws.com/v1/master/ba62fe743df0fe93366eba3a257d792884136c7f/LINEAR-859-DOCUMENTARYPLUS-DOCUMENTARYPLUS/mt/documentaryplus/859/hls/master/playlist.m3u8"] },
  { id: "curiosity", subs: true, name: "Curiosity Now", fa: "Curiosity Now", cat: "docs", badge: "CURIOSITY", color: "#1565c0",
    streams: ["https://amg00170-curiositystream-amg00170c3-rakuten-us-2289.playouts.now.amagi.tv/playlist/amg00170-curiositystreamllcfast-curiositynowrow-rakutenus/playlist.m3u8"] },
  { id: "docubay", name: "DocuBay", fa: "DocuBay", cat: "docs", badge: "DOCUBAY", color: "#004d40",
    streams: ["https://cc-mgr91yrk4pehy.akamaized.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-mgr91yrk4pehy/playlist.m3u8"] },
  { id: "bbcearth", subs: true, name: "BBC Earth", fa: "BBC Earth", cat: "docs", badge: "BBC EARTH", color: "#1b5e20",
    streams: ["https://aegis-cloudfront-1.tubi.video/bb1fc6ad-9948-42ea-aaf3-20acfcdeecac/playlist.m3u8"] },
  { id: "lovenature", subs: true, name: "Love Nature", fa: "Love Nature (حیات وحش)", cat: "docs", badge: "LOVE NATURE", color: "#2e7d32",
    streams: ["https://aegis-cloudfront-1.tubi.video/6d6d0f24-8445-4b4c-bdf6-44f9e38beaa4/playlist.m3u8", "https://mumbai-edge.smartplaytv.in/LoveNature/index.m3u8"] },
  { id: "realwild", subs: true, name: "Real Wild", fa: "Real Wild (حیات وحش)", cat: "docs", badge: "REAL WILD", color: "#33691e", streams: ["https://lds-realwild-rakuten.amagi.tv/playlist.m3u8"] },
  { id: "wildearth", name: "WildEarth", fa: "WildEarth (سافاری زنده)", cat: "docs", badge: "WILDEARTH", color: "#827717",
    streams: ["https://wildearth-ono.amagi.tv/playlist/amg01290-wildearth-oando/playlist.m3u8", "https://wildearth-xumo.amagi.tv/master.m3u8"] },
  { id: "naturetime", name: "Nature Time", fa: "Nature Time", cat: "docs", badge: "NATURE TIME", color: "#388e3c",
    streams: ["https://amg00090-amgnaturetimeemea-rakuten.amagi.tv/playlist.m3u8", "https://bamusa-naturetime-emea-eng-rakuten.amagi.tv/playlist.m3u8"] },
  { id: "terramater", subs: true, name: "Terra Mater Wild", fa: "Terra Mater Wild", cat: "docs", badge: "TERRA MATER", color: "#4e342e",
    streams: ["https://amg01775-amg01775c1-amgplt0343.playout.now3.amagi.tv/playlist/amg01775-amg01775c1-amgplt0343/playlist.m3u8"] },
  { id: "chinatravel", name: "China Travel", fa: "China Travel (سفر)", cat: "docs", badge: "CHINA TRAVEL", color: "#c62828",
    streams: ["https://fastlive.cctvplus.com/out/v1/ca6f9297b7314a63959435028af287fc/index.m3u8"] },
  { id: "dwdocs", name: "DW Documentary", fa: "DW Documentary", cat: "docs", badge: "DW DOC", color: "#0a4d8c", embed: "https://www.youtube.com/embed/videoseries?list=UUW39zufHfsuGgpLviKh297Q", urls: ["https://www.youtube.com/channel/UCW39zufHfsuGgpLviKh297Q"] },
  { id: "nasatv", name: "NASA TV", fa: "NASA TV", cat: "docs", badge: "NASA", color: "#0b3d91", embed: "https://www.youtube.com/embed/live_stream?channel=UCLA_DiR1FfKNvjuUpBHmylQ", urls: [P("NASA-TV")] },

  /* ── ورزشی ── */
  { id: "varzesh", name: "IRIB Varzesh", fa: "شبکه ورزش", cat: "sports", badge: "ورزش", color: "#1b5e20", streams: [TWB("varzesh")], embed: SEPEHR("varzesh"), urls: [SEPEHR("varzesh"), TWB_SITE("varzesh")] },
  { id: "tv3", name: "IRIB TV3", fa: "شبکه سه", cat: "sports", badge: "۳", color: "#0d47a1", streams: [TWB("tv3")], embed: SEPEHR("tv3"), urls: [SEPEHR("tv3"), TWB_SITE("tv3")] },
  { id: "persianafight", name: "Persiana Fight", fa: "پرشیانا فایت (رزمی)", cat: "sports", badge: "FIGHT", color: "#b71c1c", streams: [PERSIANA("fighthls")] },
  { id: "gemfit", name: "GEM Fit", fa: "جم فیت (ورزش و تناسب)", cat: "sports", badge: "GEM FIT", color: "#00897b", streams: [], embed: PM("GEM-Fit"), urls: [P("GEM-Fit")] },

  /* ── موسیقی ── */
  { id: "nava", name: "IRIB Nava", fa: "نوا", cat: "music", badge: "نوا", color: "#00796b", streams: [TWB("nava")], embed: SEPEHR("nava"), urls: [SEPEHR("nava"), TWB_SITE("nava")] },
  { id: "pmc", name: "PMC", fa: "PMC", cat: "music", badge: "PMC", color: "#ad1457", streams: [WNS("pmchls")], urls: [P("PMC")] },
  { id: "pmcroyale", name: "PMC Royale", fa: "PMC Royale", cat: "music", badge: "ROYALE", color: "#6a1b9a", streams: [WNS("pmcrohls")], urls: [P("PMC-Royale")] },
  { id: "4music", name: "4Music", fa: "4Music", cat: "music", badge: "4MUSIC", color: "#283593", streams: [WNS("itthls")], urls: [P("4Music")] },
  { id: "persianamusic", name: "Persiana Music", fa: "پرشیانا موزیک", cat: "music", badge: "PERSIANA MUSIC", color: "#bf360c", streams: [PERSIANA("musichls")], urls: [P("Persiana-Music")] },
  { id: "persianafolk", name: "Persiana Folk", fa: "پرشیانا موسیقی محلی", cat: "music", badge: "FOLK", color: "#8d6e63", streams: [PERSIANA("sonhls")] },
  { id: "persianavibe", name: "Persiana Vibe", fa: "پرشیانا وایب", cat: "music", badge: "VIBE", color: "#4a148c", streams: [PERSIANA("raphls")] },
  { id: "navahang", name: "Navahang TV", fa: "نواهنگ", cat: "music", badge: "NAVAHANG", color: "#00695c", streams: [WNS("simahls")] },
  { id: "gemmifa", name: "GEM Mifa", fa: "جم میفا", cat: "music", badge: "MIFA", color: "#d81b60", streams: [], embed: PM("GEM-Mifa-Plus"), urls: [P("GEM-Mifa-Plus")] },

  /* ── کودک و نوجوان ── */
  { id: "pooya", name: "IRIB Pooya", fa: "پویا و نهال", cat: "kids", badge: "پویا", color: "#f9a825", streams: [TWB("pooya")], embed: SEPEHR("pooya"), urls: [SEPEHR("pooya"), TWB_SITE("pooya")] },
  { id: "gemjunior", name: "GEM Junior", fa: "جم جونیور", cat: "kids", badge: "JUNIOR", color: "#fb8c00", streams: [], embed: PM("GEM-Junior"), urls: [P("GEM-Junior")] },
  { id: "gemkids", name: "GEM Kids", fa: "جم کیدز", cat: "kids", badge: "GEM KIDS", color: "#43a047", streams: [], embed: PM("GEM-Kids"), urls: [P("GEM-Kids")] },
  { id: "persianajunior", name: "Persiana Junior", fa: "پرشیانا جونیور", cat: "kids", badge: "JUNIOR", color: "#039be5", streams: [PERSIANA("junhls")] },
  { id: "persianateen", name: "Persiana Teen", fa: "پرشیانا تین", cat: "kids", badge: "TEEN", color: "#8e24aa", streams: [PERSIANA("kphls")] },

  /* ── سرگرمی و عمومی ── */
  { id: "manoto", name: "Manoto", fa: "منوتو", cat: "general", badge: "manoto", color: "#263238",
    streams: [], embed: PM("Manoto"), urls: [P("Manoto"), "https://www.youtube.com/@manototv/videos"] },
  { id: "tapesh", name: "Tapesh TV", fa: "تپش", cat: "general", badge: "TAPESH", color: "#b71c1c",
    streams: ["https://iptv.tapesh.tv/tapesh/playlist.m3u8"], urls: [P("Tapesh"), P("Tapesh-Iran")] },
  { id: "tapesh2", name: "Tapesh 2", fa: "تپش ۲", cat: "general", badge: "TAPESH 2", color: "#c62828", streams: [WNS("maxtvhls")] },
  { id: "persianaone", name: "Persiana One", fa: "پرشیانا وان", cat: "general", badge: "PERSIANA ONE", color: "#880e4f", urls: [P("Persiana-One")] },
  { id: "persianaplus", name: "Persiana Plus", fa: "پرشیانا پلاس", cat: "general", badge: "PERSIANA PLUS", color: "#6a1b9a", streams: [PERSIANA("euhls")] },
  { id: "persianafamily", name: "Persiana Family", fa: "پرشیانا فمیلی", cat: "general", badge: "FAMILY", color: "#ad1457", streams: [PERSIANA("familyhls")] },
  { id: "persianacomedy", name: "Persiana Comedy", fa: "پرشیانا کمدی", cat: "general", badge: "COMEDY", color: "#f57f17", streams: [PERSIANA("comedyhls")] },
  { id: "persianareality", name: "Persiana Reality", fa: "پرشیانا ریالیتی", cat: "general", badge: "REALITY", color: "#5e35b1", streams: [PERSIANA("twohls")] },
  { id: "gemlife", name: "GEM Life", fa: "جم لایف", cat: "general", badge: "GEM LIFE", color: "#00897b", streams: [], embed: PM("GEM-Life"), urls: [P("GEM-Life")] },
  { id: "gemfood", name: "GEM Food", fa: "جم فود (آشپزی)", cat: "general", badge: "GEM FOOD", color: "#ef6c00", streams: [], embed: PM("GEM-Food"), urls: [P("GEM-Food")] },
  { id: "parstv", name: "Pars TV", fa: "پارس تی‌وی", cat: "general", badge: "PARS", color: "#1565c0", streams: [WNS("parshls")], urls: [P("Pars-TV")] },
  { id: "itn", name: "ITN TV", fa: "ITN", cat: "general", badge: "ITN", color: "#0d47a1", streams: [WNS("itnhls")], urls: [P("ITN-TV")] },
  { id: "omideiran", name: "Omid-e-Iran", fa: "امید ایران", cat: "general", badge: "OITN", color: "#2e7d32", streams: [WNS("oitnhls")] },
  { id: "iccplus", name: "ICC Plus", fa: "ICC Plus", cat: "general", badge: "ICC", color: "#283593", streams: [WNS("icchls")] },
  { id: "homeplus", name: "Home Plus", fa: "هوم پلاس", cat: "general", badge: "HOME PLUS", color: "#00838f", streams: [WNS("homeplushls")] },
  { id: "erfan", name: "Erfan Halgheh", fa: "عرفان حلقه", cat: "general", badge: "عرفان", color: "#4a148c",
    streams: ["https://hls.erfanhalgheh.live/hls/stream.m3u8"], urls: [P("Erfan-Halgheh")] },

  /* ── شبکه‌های داخلی (صدا و سیما) ── */
  { id: "tv1", name: "IRIB TV1", fa: "شبکه یک", cat: "iran", badge: "۱", color: "#1565c0", streams: [TWB("tv1")], embed: SEPEHR("tv1"), urls: [SEPEHR("tv1"), TWB_SITE("tv1")] },
  { id: "tv2", name: "IRIB TV2", fa: "شبکه دو", cat: "iran", badge: "۲", color: "#2e7d32", streams: [TWB("tv2")], embed: SEPEHR("tv2"), urls: [SEPEHR("tv2"), TWB_SITE("tv2")] },
  { id: "tehran", name: "IRIB Tehran", fa: "شبکه تهران", cat: "iran", badge: "تهران", color: "#6a1b9a", streams: [TWB("tehran")], embed: SEPEHR("tehran"), urls: [SEPEHR("tehran"), TWB_SITE("tehran")] },
  { id: "nasim", name: "IRIB Nasim", fa: "نسیم", cat: "iran", badge: "نسیم", color: "#00838f", streams: [TWB("nasim")], embed: SEPEHR("nasim"), urls: [SEPEHR("nasim"), TWB_SITE("nasim")] },
  { id: "omid", name: "IRIB Omid", fa: "امید", cat: "iran", badge: "امید", color: "#ef6c00", streams: [TWB("omid")], embed: SEPEHR("omid"), urls: [SEPEHR("omid"), TWB_SITE("omid")] },
  { id: "ofogh", name: "IRIB Ofogh", fa: "افق", cat: "iran", badge: "افق", color: "#4e342e", streams: [TWB("ofogh")], embed: SEPEHR("ofogh"), urls: [SEPEHR("ofogh"), TWB_SITE("ofogh")] },
  { id: "salamat", name: "IRIB Salamat", fa: "سلامت", cat: "iran", badge: "سلامت", color: "#00897b", streams: [TWB("salamat")], embed: SEPEHR("salamat"), urls: [SEPEHR("salamat"), TWB_SITE("salamat")] },
  { id: "amouzesh", name: "IRIB Amouzesh", fa: "آموزش", cat: "iran", badge: "آموزش", color: "#3949ab", streams: [TWB("amouzesh")], embed: SEPEHR("amouzesh"), urls: [SEPEHR("amouzesh"), TWB_SITE("amouzesh")] },
  { id: "irinn", name: "IRIB News", fa: "شبکه خبر", cat: "iran", badge: "خبر", color: "#b71c1c", streams: [TWB("irinn")], embed: SEPEHR("irinn"), urls: [SEPEHR("irinn"), TWB_SITE("irinn")] },
  { id: "iribuhd", name: "IRIB UHD", fa: "فراتر (UHD)", cat: "iran", badge: "UHD", color: "#212121", streams: [TWB("faratar")] },

  /* ── اضافه‌شده‌ها: مستند، فیلم خارجی، کودک، موسیقی و آشپزی (از سرویس‌های رایگان Samsung TV Plus / Rakuten / ...) ── */
  { id: "xautentichistory", name: "Autentic History", fa: "\u0645\u0633\u062a\u0646\u062f \u062a\u0627\u0631\u06cc\u062e\u06cc", cat: "docs", streams: ["https://autentic-autentichistory-1-gb.samsung.wurl.tv/playlist.m3u8"] },
  { id: "xautentictravel", name: "Autentic Travel", fa: "\u0633\u0641\u0631", cat: "docs", streams: ["https://autentic-autentictravel-1-gb.samsung.wurl.tv/playlist.m3u8"] },
  { id: "xadventureearth", name: "Adventure Earth", fa: "\u0645\u0627\u062c\u0631\u0627\u062c\u0648\u06cc\u06cc", cat: "docs", streams: ["https://autentic-adventure-earth-1-gb.samsung.wurl.tv/playlist.m3u8"] },
  { id: "xearthtouch", name: "Earth Touch", fa: "\u062d\u06cc\u0627\u062a \u0648\u062d\u0634", cat: "docs", streams: ["https://amg01823-earthtouch-amg01823c1-samsung-gb-862.playouts.now.amagi.tv/playlist/amg01823-earthtouch-earthtouch-samsunggb/playlist.m3u8"] },
  { id: "xevolutionearth", name: "Evolution Earth", fa: "\u0637\u0628\u06cc\u0639\u062a", cat: "docs", streams: ["https://amg00276-amg00276c15-samsung-gb-3790.playouts.now.amagi.tv/playlist.m3u8"] },
  { id: "xinwild", name: "INWILD", fa: "\u062d\u06cc\u0627\u062a \u0648\u062d\u0634", cat: "docs", streams: ["https://amg00861-terninternation-inwild-samsunguk-w5wic.amagi.tv/playlist/amg00861-terninternation-inwild-samsunguk/playlist.m3u8"] },
  { id: "xintravel", name: "INTRAVEL", fa: "\u0633\u0641\u0631", cat: "docs", streams: ["https://amg00861-terncloud-amg00861c10-samsung-gb-2298.playouts.now.amagi.tv/playlist/amg00861-terninternationalfast-intravelsamsunguk-samsunggb/playlist.m3u8"] },
  { id: "xlovetheplanet", name: "Love the Planet", fa: "\u0637\u0628\u06cc\u0639\u062a", cat: "docs", streams: ["https://amg01821-lovetvchannels-lovetheplanetuksamsung-samsunguk-apopw.amagi.tv/playlist/amg01821-lovetvchannels-lovetheplanetuksamsung-samsunguk/playlist.m3u8"] },
  { id: "xwildplanet", name: "Wild Planet", fa: "\u062d\u06cc\u0627\u062a \u0648\u062d\u0634", cat: "docs", streams: ["https://d1h8whhtg5u7om.cloudfront.net/WildPlanet_GB.m3u8"] },
  { id: "xspacelive", subs: true, name: "Space Live", fa: "\u0641\u0636\u0627", cat: "docs", streams: ["https://d111bsx9oooqoh.cloudfront.net/playlist.m3u8"] },
  { id: "xpbsnature", subs: true, name: "PBS Nature", fa: "\u0637\u0628\u06cc\u0639\u062a", cat: "docs", streams: ["https://d3mr43kyql7wgk.cloudfront.net/PBS_Nature.m3u8"] },
  { id: "xpbshistory", name: "PBS History", fa: "\u062a\u0627\u0631\u06cc\u062e", cat: "docs", streams: ["https://amg02333-pbs-amg02333c1-samsung-au-1253.playouts.now.amagi.tv/playlist/amg02333-pbsdistributionfast-pbshistory-samsungau/playlist.m3u8"] },
  { id: "xpbsscience", name: "PBS Science", fa: "\u0639\u0644\u0645", cat: "docs", streams: ["https://amg02333-pbs-amg02333c13-samsung-au-6858.playouts.now.amagi.tv/playlist.m3u8"] },
  { id: "xpbstravel", subs: true, name: "PBS Travel", fa: "\u0633\u0641\u0631", cat: "docs", streams: ["https://d3hqevbyoxtkoi.cloudfront.net/PBS_Travel.m3u8"] },
  { id: "xbravewilderness", subs: true, name: "Brave Wilderness", fa: "\u062d\u06cc\u0627\u062a \u0648\u062d\u0634", cat: "docs", streams: ["https://d95zc3i1pxhs7.cloudfront.net/playlist.m3u8"] },
  { id: "xhistorywarfarenow", subs: true, name: "History & Warfare Now", fa: "\u062a\u0627\u0631\u06cc\u062e \u062c\u0646\u06af", cat: "docs", streams: ["https://d1nzda2a2b3swt.cloudfront.net/History_Warfare_Now.m3u8"] },
  { id: "xalonebyhistory", subs: true, name: "Alone By History", fa: "\u062a\u0627\u0631\u06cc\u062e", cat: "docs", streams: ["https://d3181anftsyl2u.cloudfront.net/v1/aenetworks_alone_1/samsungheadend_us/latest/main/hls/playlist.m3u8"] },
  { id: "xtastemadetravel", subs: true, name: "Tastemade Travel", fa: "\u0633\u0641\u0631", cat: "docs", streams: ["https://d6ef3usc6d9cl.cloudfront.net/Tastemade_Travel.m3u8"] },
  { id: "xtravelescapes", name: "Travel Escapes", fa: "\u0633\u0641\u0631", cat: "docs", streams: ["https://a-cdn.klowdtv.com/live3/travelescapes_720p/playlist.m3u8"] },
  { id: "x4ktraveltv", name: "4K Travel TV", fa: "\u0633\u0641\u0631", cat: "docs", streams: ["https://streams2.sofast.tv/sofastplayout/33c31ac4-51fa-46ae-afd0-0d1fe5e60a80_0_HLS/master.m3u8"] },
  { id: "xdocuvision", name: "Docu Vision", fa: "\u0645\u0633\u062a\u0646\u062f", cat: "docs", streams: ["https://streams2.sofast.tv/sofastplayout/7e8d2a51-985d-4e76-bf7e-91edf0aa6e5f_0_HLS/master.m3u8"] },
  { id: "xgreatmovies", name: "Great! Movies", fa: "\u0641\u06cc\u0644\u0645", cat: "intl", streams: ["https://amg01753-narrativeentert-greatmovies-samsunguk-7z6eh.amagi.tv/playlist/amg01753-narrativeentert-greatmovies-samsunguk/playlist.m3u8"] },
  { id: "xiconfilmchannel", subs: true, name: "Icon Film Channel", fa: "\u0641\u06cc\u0644\u0645", cat: "intl", streams: ["https://iconfilmsdistribution-iconfilmchannelclassics-1-gb.samsung.wurl.tv/playlist.m3u8"] },
  { id: "xlifetimemovies", name: "Lifetime Movies", fa: "\u0641\u06cc\u0644\u0645", cat: "intl", streams: ["https://amg00276-amg00276c21-samsung-gb-5270.playouts.now.amagi.tv/playlist.m3u8"] },
  { id: "xsparklemovies", subs: true, name: "Sparkle Movies", fa: "\u0641\u06cc\u0644\u0645", cat: "intl", streams: ["https://candlelightmedia-sparklemovies-1-gb.samsung.wurl.tv/playlist.m3u8"] },
  { id: "xrakutentopmoviesuk", name: "Rakuten Top Movies UK", fa: "\u0641\u06cc\u0644\u0645\u200c\u0647\u0627\u06cc \u0628\u0631\u062a\u0631", cat: "intl", streams: ["https://0145451975a64b35866170fd2e8fa486.mediatailor.eu-west-1.amazonaws.com/v1/master/0547f18649bd788bec7b67b746e47670f558b6b2/production-LiveChannel-5987/master.m3u8"] },
  { id: "xrakutentvactionmoviesuk", name: "Rakuten TV Action Movies UK", fa: "\u0641\u06cc\u0644\u0645 \u0627\u06a9\u0634\u0646", cat: "intl", streams: ["https://54045f0c40fd442c8b06df076aaf1e85.mediatailor.eu-west-1.amazonaws.com/v1/master/0547f18649bd788bec7b67b746e47670f558b6b2/production-LiveChannel-6065/master.m3u8"] },
  { id: "xrakutentvcomedymoviesuk", name: "Rakuten TV Comedy Movies UK", fa: "\u0641\u06cc\u0644\u0645 \u06a9\u0645\u062f\u06cc", cat: "intl", streams: ["https://9be783d652cd4b099cf63e1dc134c4a3.mediatailor.eu-west-1.amazonaws.com/v1/master/0547f18649bd788bec7b67b746e47670f558b6b2/production-LiveChannel-6181/master.m3u8"] },
  { id: "xrakutentvdramamoviesuk", name: "Rakuten TV Drama Movies UK", fa: "\u0641\u06cc\u0644\u0645 \u062f\u0631\u0627\u0645", cat: "intl", streams: ["https://fee09fd665814f51b939b6d106cf5f66.mediatailor.eu-west-1.amazonaws.com/v1/master/0547f18649bd788bec7b67b746e47670f558b6b2/production-LiveChannel-6093/master.m3u8"] },
  { id: "xrakutentvfamilymoviesuk", name: "Rakuten TV Family Movies UK", fa: "\u0641\u06cc\u0644\u0645 \u062e\u0627\u0646\u0648\u0627\u062f\u06af\u06cc", cat: "intl", streams: ["https://e3207568b726401995c25670faaf32e4.mediatailor.eu-west-1.amazonaws.com/v1/master/0547f18649bd788bec7b67b746e47670f558b6b2/production-LiveChannel-6203/master.m3u8"] },
  { id: "xrakutentvromancemoviesuk", name: "Rakuten TV Romance Movies UK", fa: "\u0641\u06cc\u0644\u0645 \u0639\u0627\u0634\u0642\u0627\u0646\u0647", cat: "intl", streams: ["https://2c88ed8c4df9479aa0c7138dc42115e2.mediatailor.eu-west-1.amazonaws.com/v1/master/0547f18649bd788bec7b67b746e47670f558b6b2/production-LiveChannel-6194/master.m3u8"] },
  { id: "xgravitasmovies", subs: true, name: "Gravitas Movies", fa: "\u0641\u06cc\u0644\u0645", cat: "intl", streams: ["https://d6dg3ebeih71x.cloudfront.net/Gravitas_Movies.m3u8"] },
  { id: "xfilmrisewesterns", subs: true, name: "FilmRise Westerns", fa: "\u0648\u0633\u062a\u0631\u0646", cat: "intl", streams: ["https://dz05z8iljgvbe.cloudfront.net/master.m3u8"] },
  { id: "xdriveinmoviechannel", name: "Drive In Movie Channel", fa: "\u0641\u06cc\u0644\u0645 \u06a9\u0644\u0627\u0633\u06cc\u06a9", cat: "intl", streams: ["https://streams2.sofast.tv/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/e5056383-20ac-488f-b299-6577f66881ff/manifest.m3u8"] },
  { id: "xnbccomedyvault", subs: true, name: "NBC Comedy Vault", fa: "\u06a9\u0645\u062f\u06cc", cat: "intl", streams: ["https://xumo-xumoent-vc-105-z0vpm.fast.nbcuni.com/live/master.m3u8"] },
  { id: "xbbccomedy", subs: true, name: "BBC Comedy", fa: "\u06a9\u0645\u062f\u06cc \u0628\u06cc\u200c\u0628\u06cc\u200c\u0633\u06cc", cat: "intl", streams: ["https://d1em2hga7sgumq.cloudfront.net/playlist.m3u8"] },
  { id: "xdrybarcomedy", subs: true, name: "Dry Bar Comedy", fa: "\u0627\u0633\u062a\u0646\u062f\u0622\u067e \u06a9\u0645\u062f\u06cc", cat: "intl", streams: ["https://drybar-drybarcomedy-1-us.samsung.wurl.tv/playlist.m3u8"] },
  { id: "xkdramabycjenm", name: "K Drama by CJ ENM", fa: "\u0633\u0631\u06cc\u0627\u0644 \u06a9\u0631\u0647\u200c\u0627\u06cc", cat: "intl", streams: ["https://d2fdocl6hmu0hh.cloudfront.net/dfa54c7d_1154_425d_a2b8_6ea994157976/hls/playlist.m3u8"] },
  { id: "xgeniekdrama", name: "Genie K Drama", fa: "\u0633\u0631\u06cc\u0627\u0644 \u06a9\u0631\u0647\u200c\u0627\u06cc", cat: "intl", streams: ["https://ads.its-newid.net/api/manifest.m3u8?ads.service_id=US2000012KX&channel_id=newid_351&tp=samsung_tvplus"] },
  { id: "xmysterysciencetheater300", subs: true, name: "Mystery Science Theater 3000", fa: "\u06a9\u0645\u062f\u06cc", cat: "intl", streams: ["https://d1c73nj8qxp55a.cloudfront.net/Mystery_Science_Theater_3000.m3u8"] },
  { id: "xdemanddrama", name: "Demand Drama", fa: "\u0633\u0631\u06cc\u0627\u0644 \u062f\u0631\u0627\u0645", cat: "intl", streams: ["https://amg01487-amg01487c3-amgplt0002.playout.now3.amagi.tv/playlist/amg01487-amg01487c3-amgplt0002/playlist.m3u8"] },
  { id: "xbbckids", name: "BBC Kids", fa: "\u06a9\u0648\u062f\u06a9 \u0628\u06cc\u200c\u0628\u06cc\u200c\u0633\u06cc", cat: "kids", streams: ["https://dmr1h4skdal9h.cloudfront.net/playlist.m3u8"] },
  { id: "xhappykids", subs: true, name: "HappyKids", fa: "\u06a9\u0648\u062f\u06a9", cat: "kids", streams: ["https://dil9xdvretp0f.cloudfront.net/index.m3u8"] },
  { id: "xloolookids", name: "LooLoo Kids", fa: "\u0634\u0639\u0631 \u06a9\u0648\u062f\u06a9", cat: "kids", streams: ["https://amg02757-amg02757c5-samsung-gb-5765.playouts.now.amagi.tv/playlist/amg02757-loolookids-llkenfast-samsunggb/playlist.m3u8"] },
  { id: "xkartoonchannel", subs: true, name: "Kartoon Channel!", fa: "\u06a9\u0627\u0631\u062a\u0648\u0646", cat: "kids", streams: ["https://d2z0ysa6dgxhlc.cloudfront.net/kchan.m3u8"] },
  { id: "xtoongoggles", name: "Toon Goggles", fa: "\u06a9\u0627\u0631\u062a\u0648\u0646", cat: "kids", streams: ["https://d1eg24xrsfr6kv.cloudfront.net/tg/tg/tg.m3u8"] },
  { id: "xcartoonclassics", name: "Cartoon Classics", fa: "\u06a9\u0627\u0631\u062a\u0648\u0646 \u06a9\u0644\u0627\u0633\u06cc\u06a9", cat: "kids", streams: ["https://streams2.sofast.tv/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/d5543c06-5122-49a7-9662-32187f48aa2c/manifest.m3u8"] },
  { id: "xmrbeananime", subs: true, name: "Mr. Bean Anime", fa: "\u0645\u0633\u062a\u0631 \u0628\u06cc\u0646", cat: "kids", streams: ["https://amg00627-amg00627c28-rakuten-uk-3984.playouts.now.amagi.tv/playlist/amg00627-banijayfast-mrbeanukcc-rakutenuk/playlist.m3u8"] },
  { id: "xxitehits", name: "XITE Hits", fa: "\u0645\u0648\u0632\u06cc\u06a9 \u0648\u06cc\u062f\u06cc\u0648", cat: "music", streams: ["https://d726x48n2pd5h.cloudfront.net/XITE_Hits.m3u8"] },
  { id: "xvevoretrorock", subs: true, name: "Vevo Retro Rock", fa: "\u0631\u0627\u06a9 \u0642\u062f\u06cc\u0645\u06cc", cat: "music", streams: ["https://d2hdqrshyzxswl.cloudfront.net/Vevo_Retro_Rock.m3u8"] },
  { id: "xnowrock", name: "NOW Rock", fa: "\u0631\u0627\u06a9", cat: "music", streams: ["https://lightning-now90s-rakuten.amagi.tv/playlist.m3u8"] },
  { id: "xqwesttvjazzbeyond", name: "Qwest TV Jazz & Beyond", fa: "\u062c\u0627\u0632", cat: "music", streams: ["https://samsungau-qwestjazz-samsungtv-zw2jc.amagi.tv/playlist/samsungau-qwestjazz-samsungtv/playlist.m3u8"] },
  { id: "xcaliforniamusicchannel", name: "California Music Channel", fa: "\u0645\u0648\u0632\u06cc\u06a9", cat: "music", streams: ["https://cmc-kowdtv.amagi.tv/playlist.m3u8"] },
  { id: "xbbcfood", subs: true, name: "BBC Food", fa: "\u0622\u0634\u067e\u0632\u06cc \u0628\u06cc\u200c\u0628\u06cc\u200c\u0633\u06cc", cat: "general", streams: ["https://d1e9r0b71zfwk7.cloudfront.net/playlist.m3u8"] },
  { id: "xpbsfood", subs: true, name: "PBS Food", fa: "\u0622\u0634\u067e\u0632\u06cc", cat: "general", streams: ["https://d3w43rc3ob044a.cloudfront.net/PBS_Food.m3u8"] },
];
}
